---
Name: subsiteconfig
After:
  - 'framework/*'
---
SilverStripe\AssetAdmin\Controller\AssetAdmin:
  treats_subsite_0_as_global: true

SilverStripe\Control\Director:
  rules:
    SubsiteXHRController: SilverStripe\Subsites\Controller\SubsiteXHRController
