---
Name: subsiteconfig
---
SilverStripe\AssetAdmin\Controller\AssetAdmin:
  treats_subsite_0_as_global: true

SilverStripe\Control\Director:
  rules:
    'SubsiteXHRController': 'SubsiteXHRController'
