---
Name: subsiteconfig
After:
 - 'framework/*'
 - 'cms/*'
---
AssetAdmin:
  treats_subsite_0_as_global: true

SilverStripe\Control\Director:
  rules:
    'SubsiteXHRController': 'SubsiteXHRController'
